# Site settings
title: Derek Tor Website
email: derekmtor@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal Website of Derek Tor. Web Developer. Javascript Developer. Front End Developer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://derektor.me" # the base hostname & protocol for your site
twitter_username: derektorq
github_username:  rundmt

# Build settings
markdown: kramdown
collections:
  projects:
    output: true
    permalink: /projects/:path/
